//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingMail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tShoppingcarmodel
    {
        public int Id { get; set; }
        public Nullable<int> fOrderId { get; set; }
        public string fUserId { get; set; }
        public Nullable<int> fPId { get; set; }
        public string fPName { get; set; }
        public Nullable<int> fPrice { get; set; }
        public Nullable<int> fMaxQty { get; set; }
        public Nullable<int> fOrderQty { get; set; }
        public string fImg { get; set; }
        public Nullable<int> fChangeQty { get; set; }
        public string fIsApproved { get; set; }
        public Nullable<int> fAId_1 { get; set; }
        public Nullable<int> fAId_2 { get; set; }
        public Nullable<int> fAId_3 { get; set; }
        public Nullable<int> fSupplyLimit { get; set; }
    }
}
